name: The Mueller-Harders
favicon: null
layout_spectrum: 0.22484
typography_spectrum: 0.3898
title: 'Being the occasional and informal journal of the Mueller-Harder family: Erik, Karen, Timothy, & Cameron.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96b8e3'
    - '#636f63'
    - '#010004'
    - '#2d2e30'
    - '#d8c7a0'
  brandStrength: 0.25
  lightness: 0.9267119511496276
  saturation: 0.5768768659327179
  rhythmicContrast: 0.5
purpose: []
